version: '3.8'
services:
  db:
    image: postgres:15
    container_name: wellness-db-container
    environment:
      POSTGRES_DB: wellness
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wellness"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth_service:
    build: ./auth_service
    container_name: auth-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/wellness
    depends_on:
      db:
        condition: service_healthy

  sentiment_service:
    build: ./sentiment_service
    container_name: sentiment-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/wellness
    depends_on:
      db:
        condition: service_healthy

  chatbot_service:
    build: ./chatbot_service
    container_name: chatbot-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/wellness
      - GOOGLE_API_KEY=
      - GOOGLE_SEARCH_API_KEY=
      - GOOGLE_SEARCH_ENGINE_ID=
      - SENTIMENT_SERVICE_URL=http://sentiment-service:8002
    volumes:
      - ./chatbot_service:/app
    depends_on:
      db:
        condition: service_healthy
      sentiment_service:
        condition: service_started

  voice_service:
    build:
      context: ./voice_service
    ports:
      - "8003:8003"
    environment:
      - CHATBOT_SERVICE_URL=http://chatbot-service:8001
    volumes:
      - ./voice_service:/app
    depends_on:
      - chatbot_service

  video_service:
    build:
      context: ./video_service
    ports:
      - "8004:8004"
    environment:
      - SENTIMENT_SERVICE_URL=http://sentiment-service:8002
    volumes:
      - ./video_service:/app
    depends_on:
      - sentiment_service

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api-gateway
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - SENTIMENT_SERVICE_URL=http://sentiment-service:8002
      - CHATBOT_SERVICE_URL=http://chatbot-service:8001
      - VOICE_SERVICE_URL=http://voice_service:8003
      - VIDEO_SERVICE_URL=http://video_service:8004
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - sentiment_service
      - chatbot_service
      - voice_service
      - video_service

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api_gateway